/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStorageIndexRouteImport } from './routes/app.storage.index'
import { Route as AppContactsIndexRouteImport } from './routes/app.contacts.index'
import { Route as AppChatsIndexRouteImport } from './routes/app.chats.index'
import { Route as AppChatsIdRouteImport } from './routes/app.chats.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStorageIndexRoute = AppStorageIndexRouteImport.update({
  id: '/storage/',
  path: '/storage/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIdRoute = AppChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/chats/$id': typeof AppChatsIdRoute
  '/app/chats/': typeof AppChatsIndexRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/storage/': typeof AppStorageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/chats/$id': typeof AppChatsIdRoute
  '/app/chats': typeof AppChatsIndexRoute
  '/app/contacts': typeof AppContactsIndexRoute
  '/app/storage': typeof AppStorageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/chats/$id': typeof AppChatsIdRoute
  '/app/chats/': typeof AppChatsIndexRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/storage/': typeof AppStorageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/chats/$id'
    | '/app/chats/'
    | '/app/contacts/'
    | '/app/storage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/chats/$id'
    | '/app/chats'
    | '/app/contacts'
    | '/app/storage'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/chats/$id'
    | '/app/chats/'
    | '/app/contacts/'
    | '/app/storage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/storage/': {
      id: '/app/storage/'
      path: '/storage'
      fullPath: '/app/storage/'
      preLoaderRoute: typeof AppStorageIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts/': {
      id: '/app/contacts/'
      path: '/contacts'
      fullPath: '/app/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chats/': {
      id: '/app/chats/'
      path: '/chats'
      fullPath: '/app/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chats/$id': {
      id: '/app/chats/$id'
      path: '/chats/$id'
      fullPath: '/app/chats/$id'
      preLoaderRoute: typeof AppChatsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatsIdRoute: typeof AppChatsIdRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppStorageIndexRoute: typeof AppStorageIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatsIdRoute: AppChatsIdRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppStorageIndexRoute: AppStorageIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
